---
title: "R practice: functions"
format: html
---

```{r}
library(rvest)
library(readr)
library(dplyr)
library(janitor)
```
```{r}
webpage <- rvest::read_html("https://www.pwrc.usgs.gov/BBL/Bander_Portal/login/speclist.php")

tbls <- rvest::html_nodes(webpage, "table") %>% 
    rvest::html_table(fill = TRUE)
#transforms html to R code

species <- tbls[[1]] %>% 
    janitor::clean_names() %>% 
  #cleans column names
    select(alpha_code, common_name) %>% 
    mutate(alpha_code = tolower(alpha_code))
#tolower makes them lowercase

head(species, 3)
```

```{r}
predator_survey <- read_csv("https://arcticdata.io/metacat/d1/mn/v2/object/urn%3Auuid%3A9ffec04c-7e2d-41dd-9e88-b6c2e8c4375e")
nest_data <- read_csv("https://arcticdata.io/metacat/d1/mn/v2/object/urn%3Auuid%3A982bd2fc-4edf-4da7-96ef-0d11b853102d")
egg_measures <- read_csv("https://arcticdata.io/metacat/d1/mn/v2/object/urn%3Auuid%3A4b219711-2282-420a-b1d6-1893fe4a74a6")
```

### q1
```{r}
glimpse(nest_data)
#5577 of 104
glimpse(predator_survey)
#2337 of 12
glimpse(egg_measures)
#18,749 of 12
```

### q3
```{r}
View(species)
View(predator_survey)
#predator_survey$species = species$alpha_code

#my attempt, renamed column
names(species)[names(species) == "alpha_code"] <- "species_code"
head(species)
pred_sp <- left_join(predator_survey, species, by = "species")
head(pred_sp)

predator_comm_names <- left_join(predator_survey,
                                 species,
                                 by = c("species" = "alpha_code"))
```


### q4
```{r}
#' Adding common names
#'
#' @param df  a dataframe containing a column 'species' with species codes
#' @param species a dataframe containing a column 'alpha_code' and 'common_names'
#'
#' @returns original dataframe df with an additional column, 'common_names' 
#' @export 
#'
#' @examples add_common(df = predator_survey, species = species)
add_common <- function(df, species) {
  df_sp <- left_join(df, #df1
            species, #df2
            by = c("species" = "alpha_code")) #col1 and col2
            return(df_sp) #new df
}

```


### q5
```{r}
head(nest_data)
#5577 of 104
nest_data1 <- nest_data %>% 
  select(!c(starts_with("unk")))
```

### extra
```{r}
#add error messages to functions

```

