---
title: "visualization with ggplot2 and beyond"
format: html
editor_options: 
  chunk_output_type: console
---

## Making nice grpahs

```{r, message=FALSE}
## set up
library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(janitor) # expedite cleaning and exploring data
library(scales) # scale functions for visualization
```

```{r, message=FALSE}
escape_raw <- read_csv("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3Af119a05b-bbe7-4aea-93c6-85434dcb1c5e")
```

```{r}
escape <- escape_raw %>% clean_names()
#505,420
```

```{r}
annual_esc <- escape %>% 
  filter(species %in% c("Sockeye", "Chum", "Pink", "Coho", "Chinook")) %>%
    #423,161
  mutate(year = lubridate::year(sample_date)) %>%
    #10 rows
  group_by(species, sasap_region, year) %>%
  summarise(escapement = sum(daily_count))
#1484   

annual_esc
```

```{r}
ggplot(data=annual_esc, mapping = aes(x = species, y = escapement)) +
  geom_col(aes(fill=species))
#totaled for all years

ggplot(data=annual_esc, mapping = aes(x = species, y = escapement)) +
  geom_point(aes(color = year))
```

```{r}
annual_esc %>% 
  filter(year == 1974, species %in% c("Chum","Pink")) %>%
  ggplot(aes(x=species, y=escapement)) +
  geom_violin() +
  geom_point() 


```

## Making nice tables
```{r}
library(DT)

locations <- escape %>% 
  distinct(location, latitude, longitude) %>% 
  drop_na()

datatable(locations)
#creates a javascript embedded table that you can control for # of entries, etc

```

## Mapping with leaflet
```{r}
library(leaflet)

leaflet(locations) %>% 
  addTiles() %>% 
  addMarkers(
      lng = ~ longitude, 
      lat = ~ latitude, 
      popup = ~ locations
  )
```

```{r}
leaflet(locations) %>%
  #loads map images from the web
    addWMSTiles(
        "https://wms.gebco.net/mapserv?request=getmap&service=wms&BBOX=-90,-180,90,360&crs=EPSG:4326&format=image/jpeg&layers=gebco_latest&width=1200&height=600&version=1.3.0",
        layers = 'GEBCO_LATEST',
        attribution = "Imagery reproduced from the GEBCO_2022 Grid, WMS 1.3.0 GetMap, www.gebco.net"
    ) %>%
    addCircleMarkers(
        lng = ~ longitude,
        lat = ~ latitude,
        popup = ~ location,
        radius = 5,
        # set fill properties
        fillColor = "salmon",
        fillOpacity = 1,
        # set stroke properties
        stroke = TRUE,
        weight = 0.5,
        color = "white",
        opacity = 1
    )
```

